### ISSUE TITLE
Saving XMP gives error if xmp already exists

### ISSUE THREAD

**Issue by Hicetnunc** [ncruces/RethinkRAW#1]
If you start developing an image again that was developed before, saving the xmp produces an error if a xmp file already exists. The changes are nevertheless saved.

**Comment by ncruces** [comment]
Yes, thank you for the report!
This was introduced in 9f170b8c28dee723728c8ebe3c138d155c3a61d0.

**Comment by ncruces** [comment]
This will be included in the next beta, released probably tomorrow.

**Comment by ncruces** [comment]
[Released](https://github.com/ncruces/RethinkRAW/releases/tag/v0.3.0).
